version: '3.8'

services:
  backend:
    build: ./backend/backend
    container_name: institute-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: local
      MYSQL_URL: jdbc:mysql://db:3306/ims?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: institute-frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend

  db:
    image: mysql:8
    container_name: institute-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ims
    ports:
      - "3306:3306"
